
    # JPA / HIBERNATE / DEV
    spring.dev.datasource.url=jdbc:oracle:thin:@10.181.80.4:1521/pr1.localdomain
    spring.dev.datasource.username=desa8
    spring.dev.datasource.password=desa8
    spring.dev.datasource.driver-class-name=oracle.jdbc.OracleDriver
    # JPA / HIBERNATE / PRD
    spring.prd.datasource.url=jdbc:oracle:thin:@10.100.16.204:1521:pr1
    spring.prd.datasource.username=prod1u
    spring.prd.datasource.password=prod1u
    spring.prd.datasource.driver-class-name=oracle.jdbc.OracleDriver
    # JPA
#    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
#    spring.jpa.show-sql=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

    spring.datasource.hikari.minimum-idle=5
    spring.datasource.hikari.maximum-pool-size=20
    spring.datasource.hikari.idle-timeout=30000
    spring.datasource.hikari.max-lifetime=1800000
    spring.datasource.hikari.connection-timeout=30000


    spring.jpa.properties.hibernate.jdbc.batch_size=400
    spring.jpa.properties.hibernate.jdbc.fetch_size=400
    spring.jpa.properties.hibernate.order_inserts=true
    spring.jpa.properties.hibernate.order_updates=true


    server.tomcat.threads.min-spare=10
    server.tomcat.threads.max=200
    spring.threads.virtual.enabled=true


    #SWAGGER
    spring.mvc.pathmatch.matching-strategy=ant-path-matcher

    #dates
    spring.jackson.serialization.write-dates-as-timestamps=false

    #port
    server.port=8080
    server.compression.enabled=true
    server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    server.compression.min-response-size=1024

    #Others
    spring.servlet.multipart.enabled=true
    spring.servlet.multipart.file-size-threshold=2KB
    spring.servlet.multipart.max-file-size=200MB
    spring.servlet.multipart.max-request-size=215MB
